<?php
/**
 * Lucide icon search tags, for the Marker Studio icon picker search.
 *
 * Each entry maps an icon slug to the keyword tags Lucide itself uses on
 * lucide.dev, so the picker search finds "food" or "restaurant" the same way
 * the official site does -- not just by icon name.
 *
 * GENERATED FILE -- do not edit by hand.
 *
 * @since 3.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

return [
    // Pins & shapes.
    'map-pin' => ['location', 'waypoint', 'marker', 'drop'],
    'map-pinned' => ['location', 'waypoint', 'marker', 'drop'],
    'pin' => ['save', 'map', 'lock', 'fix'],
    'navigation' => ['location', 'travel'],
    'compass' => ['direction', 'north', 'east', 'south', 'west', 'browser'],
    'crosshair' => ['aim', 'target'],
    'circle' => ['off', 'zero', 'record', 'shape'],
    'square' => ['stop', 'playback', 'music', 'audio', 'video', 'rectangle', 'aspect ratio', '1:1', 'shape'],
    'star' => ['bookmark', 'favorite', 'like', 'review', 'rating'],
    'flag' => ['report', 'marker', 'notification', 'warning', 'milestone', 'goal', 'notice', 'signal', 'attention', 'banner'],
    'bookmark' => ['save', 'favorite', 'mark', 'label', 'attachment', 'file', 'stick', 'pin', 'read', 'clip', 'marker', 'tag'],
    'route' => ['path', 'journey', 'planner', 'points', 'stops', 'stations'],
    'signpost' => ['navigation', 'direction', 'arrow', 'wayfinding', 'guide', 'location', 'pointer', 'route', 'indicator', 'marker', 'bidirectional', 'left', 'right', 'east', 'west'],
    'milestone' => ['signpost', 'direction', 'right', 'east', 'forward', 'version control', 'waypoint'],
    'target' => ['logo', 'bullseye', 'deadline', 'projects', 'overview', 'work', 'productivity'],

    // Retail & shopping.
    'store' => ['shop', 'supermarket', 'stand', 'boutique', 'building'],
    'shopping-bag' => ['ecommerce', 'cart', 'purchase', 'store'],
    'shopping-cart' => ['trolley', 'cart', 'basket', 'e-commerce', 'store', 'purchase', 'products', 'items', 'ingredients'],
    'shopping-basket' => ['cart', 'e-commerce', 'store', 'purchase', 'products', 'items', 'ingredients'],
    'warehouse' => ['storage', 'storehouse', 'depot', 'depository', 'repository', 'stockroom', 'logistics', 'building'],
    'gift' => ['present', 'box', 'birthday', 'party'],
    'tag' => ['label', 'badge', 'ticket', 'mark'],
    'percent' => ['percentage', 'modulo', 'modulus', 'remainder', '%', 'sale', 'discount', 'offer', 'marketing'],
    'receipt' => ['bill', 'voucher', 'slip', 'check', 'counterfoil', 'currency', 'dollar', 'usd', '$'],
    'package' => ['box', 'container', 'storage', 'sealed', 'delivery', 'undelivered', 'unopened', 'packed', 'archive', 'zip', 'module'],
    'barcode' => ['scan', 'checkout', 'till', 'cart', 'transaction', 'purchase', 'buy', 'product', 'packaging', 'retail', 'consumer'],
    'shirt' => ['t-shirt', 'shopping', 'store', 'clothing', 'clothes'],
    'gem' => ['diamond', 'crystal', 'ruby', 'jewellery', 'price', 'special', 'present', 'gift', 'ring', 'wedding', 'proposal', 'marriage', 'rubygems', 'jewelry'],
    'diamond' => ['square', 'rectangle', 'oblique', 'rhombus', 'shape', 'suit', 'playing', 'cards', 'jewelry'],
    'sparkles' => ['stars', 'effect', 'filter', 'night', 'magic'],
    'smartphone' => ['phone', 'cellphone', 'device', 'screen'],
    'laptop' => ['computer', 'screen', 'remote'],
    'monitor' => ['tv', 'screen', 'display', 'virtual machine', 'vm'],
    'tablet' => ['device'],
    'headphones' => ['music', 'audio', 'sound'],
    'toy-brick' => ['lego', 'block', 'addon', 'plugin', 'integration', 'toy', 'toys', 'playground'],
    'puzzle' => ['component', 'module', 'part', 'piece'],
    'sofa' => ['armchair', 'furniture', 'leisure', 'lounge', 'loveseat', 'couch'],
    'armchair' => ['sofa', 'furniture', 'leisure', 'lounge', 'loveseat', 'couch'],
    'lamp' => ['lighting', 'household', 'home', 'furniture'],
    'lamp-desk' => ['lighting', 'household', 'office', 'desk', 'home', 'furniture'],
    'glasses' => ['glasses', 'spectacles', 'optician', 'optometry', 'eyewear'],
    'cat' => ['animal', 'pet', 'kitten', 'feline'],
    'bird' => ['peace', 'freedom', 'wing', 'avian', 'tweet'],
    'rabbit' => ['animal', 'rodent', 'pet', 'pest', 'bunny', 'hare', 'fast', 'speed', 'hop'],
    'turtle' => ['animal', 'pet', 'tortoise', 'slow', 'speed'],
    'bone' => ['health', 'skeleton', 'skull', 'death', 'pets', 'dog'],
    'shovel' => ['dig', 'spade', 'treasure', 'gardening', 'garden', 'landscaping'],

    // Food & drink.
    'coffee' => ['drink', 'cup', 'mug', 'tea', 'cafe', 'hot', 'beverage'],
    'cup-soda' => ['beverage', 'cup', 'drink', 'soda', 'straw', 'water'],
    'utensils' => ['fork', 'knife', 'cutlery', 'flatware', 'tableware', 'silverware', 'food', 'restaurant', 'meal', 'breakfast', 'dinner', 'supper'],
    'utensils-crossed' => ['fork', 'knife', 'cutlery', 'flatware', 'tableware', 'silverware', 'food', 'restaurant', 'meal', 'breakfast', 'dinner', 'supper'],
    'pizza' => ['pie', 'quiche', 'food'],
    'sandwich' => ['food', 'snack', 'dish', 'restaurant', 'lunch', 'meal'],
    'soup' => ['food', 'dish', 'restaurant', 'course', 'meal', 'bowl', 'starter'],
    'salad' => ['food', 'vegetarian', 'dish', 'restaurant', 'course', 'meal', 'side', 'vegetables', 'health'],
    'fish' => ['dish', 'restaurant', 'course', 'meal', 'seafood', 'pet', 'sea', 'marine'],
    'drumstick' => ['food', 'chicken', 'meat'],
    'cake' => ['birthday', 'birthdate', 'celebration', 'party', 'surprise', 'gateaux', 'dessert', 'fondant', 'icing sugar', 'sweet', 'baking'],
    'cookie' => ['biscuit', 'privacy', 'legal', 'food'],
    'croissant' => ['bakery', 'cooking', 'food', 'pastry'],
    'ice-cream-cone' => ['gelato', 'food'],
    'beer' => ['alcohol', 'bar', 'beverage', 'brewery', 'drink'],
    'wine' => ['alcohol', 'beverage', 'bar', 'drink', 'glass', 'sommelier', 'vineyard', 'winery'],
    'apple' => ['fruit', 'food', 'healthy', 'snack', 'nutrition', 'fresh', 'produce', 'grocery', 'organic', 'harvest', 'vitamin', 'red', 'green', 'juicy', 'sweet', 'tart', 'bite', 'orchard', 'plant', 'core', 'raw', 'diet'],
    'carrot' => ['orange', 'healthy', 'nature', 'fresh', 'root', 'produce', 'organic', 'nutrition', 'vegetable', 'food', 'eat'],
    'wheat' => ['corn', 'cereal', 'grain', 'gluten'],
    'grape' => ['fruit', 'wine', 'food'],
    'beef' => ['food', 'dish', 'restaurant', 'course', 'meal', 'meat', 'bbq', 'steak'],
    'ham' => ['food', 'pork', 'pig', 'meat', 'bone', 'hock', 'knuckle', 'gammon', 'cured'],
    'egg' => ['bird', 'chicken', 'nest', 'hatch', 'shell', 'incubate', 'soft boiled', 'hard', 'breakfast', 'brunch', 'morning', 'easter'],
    'martini' => ['cocktail', 'alcohol', 'beverage', 'bar', 'drink', 'glass', 'spirit', 'party', 'celebration', 'mixer'],
    'glass-water' => ['beverage', 'drink', 'glass', 'water'],
    'chef-hat' => ['cooking', 'food', 'kitchen', 'restaurant'],
    'cooking-pot' => ['pod', 'cooking', 'recipe', 'food', 'kitchen', 'chef', 'restaurant', 'dinner', 'lunch', 'breakfast', 'meal', 'eat'],
    'donut' => ['doughnut', 'sprinkles', 'topping', 'fast food', 'junk food', 'snack', 'treat', 'sweet', 'sugar', 'dessert', 'hollow', 'ring'],
    'candy' => ['sugar', 'food', 'sweet'],
    'ice-cream' => ['dessert', 'sweet', 'frozen', 'treat'],
    'sprout' => ['eco', 'green', 'growth', 'leaf', 'nature', 'plant', 'seed', 'spring', 'sustainability'],

    // Transport & fuel.
    'car' => ['vehicle', 'drive', 'trip', 'journey'],
    'bus' => ['bus', 'vehicle', 'transport', 'trip'],
    'train-front' => ['railway', 'metro', 'subway', 'underground', 'high-speed', 'bullet', 'fast', 'track', 'line'],
    'tram-front' => ['railway', 'metro', 'subway', 'underground', 'track', 'line', 'tourism'],
    'plane' => ['plane', 'trip', 'airplane', 'fly', 'flying', 'flight', 'aviation'],
    'ship' => ['boat', 'knots', 'nautical mile', 'maritime', 'sailing', 'yacht', 'cruise', 'ocean liner', 'tanker', 'vessel', 'navy', 'trip', 'releases'],
    'sailboat' => ['ship', 'boat', 'harbor', 'harbour', 'dock'],
    'anchor' => ['ship'],
    'bike' => ['bicycle', 'transport', 'trip'],
    'truck' => ['delivery', 'van', 'shipping', 'haulage', 'lorry'],
    'caravan' => ['trailer', 'tow', 'camping', 'campsite', 'mobile home', 'holiday', 'nomadic', 'wilderness', 'outdoors'],
    'fuel' => ['filling-station', 'gas', 'petrol', 'tank'],
    'battery-charging' => ['power', 'electricity', 'energy', 'accumulator', 'charge'],
    'circle-parking' => ['parking lot', 'car park'],
    'car-taxi-front' => ['cab', 'vehicle', 'drive', 'trip', 'journey', 'taxi'],
    'cable-car' => ['ski lift', 'winter holiday', 'alpine', 'resort', 'mountains'],
    'plane-landing' => ['arrival', 'plane', 'trip', 'airplane', 'landing', 'fly', 'flying', 'flight', 'aviation'],
    'plane-takeoff' => ['departure', 'plane', 'trip', 'airplane', 'takeoff', 'fly', 'flying', 'flight', 'aviation'],
    'helicopter' => ['transport', 'flying', 'rotor', 'aviation', 'helipad', 'gear', 'flyer', 'technology', 'helicopter', 'aircraft', 'vehicle'],
    'tractor' => ['farming', 'farmer', 'ranch', 'harvest', 'equipment', 'vehicle'],
    'parking-square' => ['parking', 'car', 'vehicle'],
    'parking-meter' => ['driving', 'car park', 'pay', 'sidewalk', 'pavement'],
    'road' => ['road', 'street', 'highway', 'route', 'path', 'transport', 'traffic', 'drive', 'map'],
    'traffic-cone' => ['roadworks', 'tarmac', 'safety', 'block'],
    'construction' => ['roadwork', 'maintenance', 'blockade', 'barricade'],
    'train' => ['train', 'railway', 'transport', 'locomotive'],
    'bus-front' => ['coach', 'vehicle', 'trip', 'road'],
    'motorbike' => ['moto', 'motorcycle', 'transport', 'vehicle', 'drive', 'ride', 'trip', 'race', 'racing', 'journey', 'delivery'],

    // Services & trades.
    'landmark' => ['bank', 'building', 'capitol', 'finance', 'money', 'museum', 'art gallery', 'hall', 'institute', 'pediment', 'portico', 'doric', 'columns', 'pillars', 'classical', 'architecture', 'government', 'institution', 'monument', 'site', 'history', 'historic', 'library', 'temple', 'ancient', 'structure'],
    'credit-card' => ['bank', 'purchase', 'payment', 'cc'],
    'banknote' => ['currency', 'money', 'payment'],
    'piggy-bank' => ['money', 'savings'],
    'wallet' => ['money', 'finance', 'pocket'],
    'briefcase' => ['work', 'bag', 'baggage', 'folder'],
    'mail' => ['email', 'message', 'letter', 'unread'],
    'phone' => ['call'],
    'printer' => ['fax', 'office', 'device'],
    'key' => ['password', 'login', 'authentication', 'secure', 'unlock', 'keychain', 'key ring', 'fob'],
    'wrench' => ['account', 'settings', 'spanner', 'diy', 'toolbox', 'build', 'construction', 'mechanic', 'plumber'],
    'hammer' => ['mallet', 'nails', 'diy', 'toolbox', 'build', 'construction', 'builder'],
    'scissors' => ['cut', 'snip', 'chop', 'stationery', 'crafts', 'barber', 'salon', 'hairdresser'],
    'paintbrush' => ['brush', 'paintbrush', 'design', 'color', 'colour', 'decoration', 'diy', 'painter', 'decorator'],
    'gavel' => ['justice', 'law', 'court', 'judgment', 'legal', 'hands', 'penalty', 'decision', 'authority', 'hammer', 'mallet'],
    'plug' => ['electricity', 'energy', 'electronics', 'socket', 'outlet', 'power', 'voltage', 'current', 'charger', 'electrician', 'electrical'],
    'plug-zap' => ['electricity', 'energy', 'electronics', 'charge', 'charging', 'battery', 'connect'],
    'zap' => ['flash', 'camera', 'lightning', 'electricity', 'energy', 'power', 'quick'],
    'lightbulb' => ['idea', 'bright', 'lights', 'electrician', 'lighting'],
    'droplet' => ['water', 'weather', 'liquid', 'fluid', 'wet', 'moisture', 'damp', 'bead', 'globule'],
    'droplets' => ['water', 'weather', 'liquid', 'fluid', 'wet', 'moisture', 'damp', 'bead', 'globule'],
    'pipette' => ['eye dropper', 'color picker', 'lab', 'chemistry'],
    'hard-hat' => ['helmet', 'construction', 'safety', 'savety'],
    'drill' => ['power', 'bit', 'head', 'hole', 'diy', 'toolbox', 'build', 'construction'],
    'ruler' => ['measurements', 'centimeters', 'cm', 'millimeters', 'mm', 'metre', 'foot', 'feet', 'inches', 'units', 'size', 'length', 'width', 'height', 'dimensions', 'depth', 'breadth', 'extent', 'stationery'],
    'paint-roller' => ['brush', 'color', 'colour', 'decoration', 'diy'],
    'scale' => ['balance', 'legal', 'license', 'right', 'rule', 'law', 'justice', 'weight', 'measure', 'compare', 'judge', 'fair', 'ethics', 'decision'],
    'calculator' => ['count', 'calculating machine'],
    'file-signature' => ['contract', 'sign', 'document', 'signature', 'agreement'],
    'stamp' => ['mark', 'print', 'clone', 'loyalty', 'library'],
    'trending-up' => ['statistics'],
    'trending-down' => ['statistics'],
    'chart-line' => ['statistics', 'analytics', 'diagram', 'graph'],
    'chart-candlestick' => ['trading', 'trader', 'financial', 'markets', 'portfolio', 'assets', 'prices', 'value', 'valuation', 'commodities', 'currencies', 'currency', 'stocks', 'exchange', 'hedge fund', 'statistics', 'analytics', 'diagram', 'graph'],
    'bitcoin' => ['cryptocurrency', 'digital', 'blockchain', 'finance', 'coin', 'market', 'decentralized', 'investment', 'crypto', 'currency', 'money', 'payment'],
    'coins' => ['money', 'cash', 'finance', 'gamble'],
    'circle-dollar-sign' => ['monetization', 'marketing', 'currency', 'money', 'payment'],
    'dollar-sign' => ['currency', 'money', 'payment'],
    'euro' => ['currency', 'money', 'payment'],
    'pound-sterling' => ['currency', 'money', 'payment'],
    'shield-check' => ['cybersecurity', 'secured', 'safety', 'protection', 'protected', 'guardian', 'guarded', 'armored', 'armoured', 'defense', 'defence', 'defended', 'blocked', 'threat', 'prevention', 'prevented', 'antivirus', 'vigilance', 'vigilant', 'active', 'activated', 'enabled', 'detection', 'scanned', 'found', 'strength', 'strong', 'tough', 'invincible', 'invincibility', 'invulnerable', 'undamaged', 'audited', 'admin', 'verification', 'verified', 'certification', 'certified', 'tested', 'passed', 'qualified', 'cleared', 'cleaned', 'disinfected', 'uninfected', 'task', 'completed', 'todo', 'done', 'ticked', 'checked', 'crest', 'bravery'],
    'shield-alert' => ['unshielded', 'cybersecurity', 'insecure', 'unsecured', 'safety', 'unsafe', 'protection', 'unprotected', 'guardian', 'unguarded', 'unarmored', 'unarmoured', 'defenseless', 'defenceless', 'undefended', 'defender', 'blocked', 'stopped', 'intercepted', 'interception', 'saved', 'thwarted', 'threat', 'prevention', 'unprevented', 'antivirus', 'vigilance', 'vigilant', 'detection', 'detected', 'scanned', 'found', 'exploit', 'vulnerability', 'vulnerable', 'weakness', 'infection', 'infected', 'comprimised', 'data leak', 'audited', 'admin', 'verification', 'unverified', 'uncertified', 'warning', 'emergency', 'attention', 'urgent', 'alarm', 'crest', 'bravery', 'strength', 'tough', 'attacked', 'damaged', 'injured', 'hit', 'expired', 'disabled', 'inactive', 'error', 'exclamation mark', '!'],
    'badge' => ['check', 'verified', 'unverified'],
    'badge-check' => ['verified', 'check'],
    'spray-can' => ['paint', 'color', 'graffiti', 'decoration', 'aerosol', 'deodorant', 'shaving foam', 'air freshener'],
    'fan' => ['air', 'cooler', 'ventilation', 'ventilator', 'blower'],
    'air-vent' => ['air conditioner', 'ac', 'central air', 'cooling', 'climate-control', 'hvac'],
    'thermometer' => ['temperature', 'celsius', 'fahrenheit', 'weather', 'hvac'],
    'anvil' => ['metal', 'iron', 'alloy', 'materials', 'heavy', 'weight', 'blacksmith', 'forge', 'acme'],

    // Health & care.
    'hospital' => ['infirmary', 'sanatorium', 'healthcare', 'doctor', 'hospice', 'clinic', 'emergency room', 'ward', 'building', 'medical', 'vet'],
    'ambulance' => ['ambulance', 'emergency', 'medical', 'vehicle', 'siren', 'healthcare', 'transportation', 'rescue', 'urgent', 'first aid'],
    'stethoscope' => ['phonendoscope', 'medical', 'heart', 'lungs', 'sound', 'doctor', 'physician'],
    'syringe' => ['medicine', 'medical', 'needle', 'pump', 'plunger', 'nozzle', 'blood', 'injection', 'vaccine', 'vaccination'],
    'pill' => ['medicine', 'medication', 'drug', 'prescription', 'tablet', 'pharmacy', 'drugstore'],
    'bandage' => ['plaster', 'band-aid', 'first aid', 'medical', 'health', 'wound', 'injury', 'care', 'treatment', 'healing', 'protection', 'emergency', 'aid', 'safety', 'patch'],
    'heart-pulse' => ['heartbeat', 'pulse', 'health', 'medical', 'blood pressure', 'cardiac', 'systole', 'diastole'],
    'cross' => ['healthcare', 'first aid'],
    'brain' => ['medical', 'mind', 'mental', 'intellect', 'cerebral', 'consciousness', 'genius', 'artificial intelligence', 'ai', 'think', 'thought', 'insight', 'intelligent', 'smart'],
    'eye' => ['view', 'watch', 'see', 'show', 'expose', 'reveal', 'display', 'visible', 'visibility', 'vision', 'preview', 'read', 'optometry', 'optician', 'eyewear'],
    'baby' => ['child', 'childproof', 'children'],
    'dog' => ['animal', 'pet', 'puppy', 'hound', 'canine'],
    'paw-print' => ['pets', 'vets', 'veterinarian', 'domesticated', 'cat', 'dog', 'bear'],
    'smile' => ['emoji', 'face', 'happy', 'good', 'emotion'],
    'activity' => ['pulse', 'action', 'motion', 'movement', 'exercise', 'fitness', 'healthcare', 'heart rate monitor', 'vital signs', 'vitals', 'emergency room', 'er', 'intensive care', 'hospital', 'defibrillator', 'earthquake', 'siesmic', 'magnitude', 'richter scale', 'aftershock', 'tremor', 'shockwave', 'audio', 'waveform', 'synthesizer', 'synthesiser', 'music'],
    'heart' => ['like', 'love', 'emotion', 'suit', 'playing', 'cards'],
    'leaf' => ['sustainability', 'nature', 'energy', 'plant', 'autumn'],
    'flower-2' => ['sustainability', 'nature', 'plant'],
    'rose' => ['roses', 'thorns', 'petals', 'plant', 'stem', 'leaves', 'spring', 'bloom', 'blossom', 'gardening', 'botanical', 'flora', 'florist', 'bouquet', 'bunch', 'gift', 'date', 'romance', 'romantic', 'valentines day', 'special occasion'],
    'ear' => ['hearing', 'noise', 'audio', 'accessibility', 'audiology'],
    'ear-off' => ['hearing', 'hard of hearing', 'hearing loss', 'deafness', 'noise', 'silence', 'audio', 'accessibility'],
    'eye-off' => ['view', 'watch', 'see', 'hide', 'conceal', 'mask', 'hidden', 'visibility', 'vision'],

    // Leisure & culture.
    'music' => ['note', 'quaver', 'eighth note'],
    'mic' => ['record', 'sound', 'listen', 'radio', 'podcast', 'microphone'],
    'guitar' => ['acoustic', 'instrument', 'strings', 'riff', 'rock', 'band', 'country', 'concert', 'performance', 'play', 'lead', 'loud', 'music', 'audio', 'sound', 'noise'],
    'film' => ['movie', 'video', 'reel', 'camera', 'cinema', 'entertainment'],
    'drama' => ['drama', 'masks', 'theater', 'theatre', 'entertainment', 'show'],
    'camera' => ['photography', 'lens', 'focus', 'capture', 'shot', 'visual', 'image', 'device', 'equipment', 'photo', 'webcam', 'video'],
    'palette' => ['colors', 'colours', 'theme', 'scheme', 'paint', 'watercolor', 'watercolour', 'artist'],
    'book' => ['reading', 'paperback', 'booklet', 'magazine', 'leaflet', 'pamphlet', 'tome', 'library', 'writing', 'written', 'writer', 'author', 'story', 'script', 'fiction', 'novel', 'information', 'knowledge', 'education', 'high school', 'university', 'college', 'academy', 'student', 'study', 'learning', 'homework', 'research', 'documentation'],
    'book-open' => ['reading', 'pages', 'booklet', 'magazine', 'leaflet', 'pamphlet', 'library', 'writing', 'written', 'writer', 'author', 'story', 'script', 'screenplay', 'fiction', 'novel', 'information', 'knowledge', 'education', 'high school', 'university', 'college', 'academy', 'student', 'study', 'learning', 'homework', 'research', 'documentation', 'revealed', 'blank', 'plain'],
    'ticket' => ['entry', 'pass', 'voucher', 'event', 'concert', 'show', 'perforated', 'dashed'],
    'trophy' => ['prize', 'sports', 'winner', 'achievement', 'award', 'champion', 'celebration', 'victory', 'competition', 'tournament', 'leaderboard', 'ranking', 'success', 'reward', 'cup', 'first', 'gold'],
    'dumbbell' => ['barbell', 'weight', 'workout', 'gym'],
    'volleyball' => ['beach', 'sand', 'net', 'holiday', 'vacation', 'summer', 'soccer', 'football', 'futbol', 'kick', 'pitch', 'goal', 'score', 'bounce', 'leather', 'wool', 'yarn', 'knitting', 'sewing', 'thread', 'embroidery', 'textile'],
    'gamepad-2' => ['console'],
    'party-popper' => ['emoji', 'congratulations', 'celebration', 'party', 'tada', '🎉', '🎊', 'excitement', 'exciting', 'excites', 'confetti'],
    'clapperboard' => ['movie', 'film', 'video', 'camera', 'cinema', 'cut', 'action', 'television', 'tv', 'show', 'entertainment'],
    'popcorn' => ['cinema', 'movies', 'films', 'salted', 'sweet', 'sugar', 'candy', 'snack'],
    'theater' => ['theater', 'theatre', 'entertainment', 'podium', 'stage', 'musical'],
    'ferris-wheel' => ['big wheel', 'daisy wheel', 'observation', 'attraction', 'entertainment', 'amusement park', 'theme park', 'funfair'],
    'roller-coaster' => ['attraction', 'entertainment', 'amusement park', 'theme park', 'funfair'],
    'dices' => ['dice', 'random', 'tabletop', 'board', 'game', 'casino', 'gambling'],
    'spade' => ['shape', 'suit', 'playing', 'cards'],
    'club' => ['shape', 'suit', 'playing', 'cards'],
    'piano' => ['music', 'audio', 'sound', 'noise', 'notes', 'chord', 'keys', 'octave', 'acoustic', 'instrument', 'play', 'pianist', 'performance', 'concert'],
    'drum' => ['drummer', 'kit', 'sticks', 'instrument', 'beat', 'bang', 'bass', 'backing track', 'band', 'play', 'performance', 'concert', 'march', 'music', 'audio', 'sound', 'noise', 'loud'],
    'disc' => ['album', 'music', 'songs', 'format', 'cd', 'dvd', 'vinyl', 'sleeve', 'cover', 'platinum', 'compilation', 'ep', 'recording', 'playback', 'spin', 'rotate', 'rpm', 'dj'],
    'frame' => ['logo', 'design', 'tool'],
    'brush' => ['clean', 'sweep', 'refactor', 'remove', 'draw', 'paint', 'color', 'artist'],
    'tickets' => ['trip', 'travel', 'pass', 'entry', 'voucher', 'event', 'concert', 'show', 'perforated', 'dashed'],
    'medal' => ['prize', 'sports', 'winner', 'trophy', 'award', 'achievement'],
    'award' => ['achievement', 'badge', 'rosette', 'prize', 'winner'],
    'crown' => ['diadem', 'tiara', 'circlet', 'corona', 'king', 'ruler', 'winner', 'favourite'],

    // Outdoors & nature.
    'tree-pine' => ['tree', 'pine', 'forest', 'park', 'nature'],
    'trees' => ['tree', 'forest', 'park', 'nature'],
    'flower' => ['sustainability', 'nature', 'plant', 'spring'],
    'mountain' => ['climb', 'hike', 'rock'],
    'waves' => ['beach', 'ocean', 'sea', 'surf', 'water'],
    'sun' => ['brightness', 'weather', 'light', 'summer'],
    'umbrella' => ['rain', 'weather'],
    'footprints' => ['steps', 'walking', 'foot', 'feet', 'trail', 'shoe'],
    'snowflake' => ['cold', 'weather', 'freeze', 'snow', 'winter'],
    'mountain-snow' => ['alpine', 'climb', 'snow'],
    'tree-deciduous' => ['tree', 'forest', 'park', 'nature'],
    'tree-palm' => ['vacation', 'leisure', 'island'],
    'palmtree' => ['beach', 'tropical', 'palm', 'vacation'],
    'cloud' => ['weather'],
    'cloud-rain' => ['weather', 'rainfall'],
    'cloud-sun' => ['weather', 'partly'],
    'cloud-snow' => ['weather', 'blizzard'],
    'rainbow' => ['colors', 'colours', 'spectrum', 'light', 'prism', 'arc', 'clear', 'sunshine'],
    'wind' => ['weather', 'air', 'blow'],
    'clover' => ['leaf', 'luck', 'plant'],
    'leafy-green' => ['salad', 'lettuce', 'vegetable', 'chard', 'cabbage', 'bok choy'],

    // Lodging.
    'bed' => ['sleep', 'hotel', 'furniture'],
    'bed-double' => ['sleep', 'hotel', 'furniture'],
    'hotel' => ['building', 'hostel', 'motel', 'inn'],
    'house' => ['home', 'living', 'building', 'residence', 'architecture'],
    'building' => ['organisation', 'organization'],
    'building-2' => ['business', 'company', 'enterprise', 'skyscraper', 'organisation', 'organization', 'city'],
    'tent' => ['tipi', 'teepee', 'wigwam', 'lodge', 'camping', 'campsite', 'holiday', 'retreat', 'nomadic', 'native american', 'indian', 'wilderness', 'outdoors'],
    'concierge-bell' => ['reception', 'bell', 'porter'],
    'key-round' => ['password', 'login', 'authentication', 'secure', 'unlock'],
    'home' => ['house', 'residence', 'home', 'living'],
    'castle' => ['fortress', 'stronghold', 'palace', 'chateau', 'building', 'monument', 'tourism'],
    'tent-tree' => ['camping', 'campsite', 'holiday', 'retreat', 'nomadic', 'wilderness', 'outdoors'],
    'door-open' => ['entrance', 'entry', 'exit', 'ingress', 'egress', 'gate', 'gateway', 'emergency exit'],
    'door-closed' => ['entrance', 'entry', 'exit', 'ingress', 'egress', 'gate', 'gateway', 'emergency exit'],

    // Public services & amenities.
    'school' => ['building', 'education', 'childhood', 'university', 'learning', 'campus', 'scholar', 'student', 'lecture', 'degree', 'course', 'academia', 'study', 'knowledge', 'classroom', 'research', 'diploma', 'graduation', 'professor', 'tutorial', 'homework', 'assignment', 'exam'],
    'graduation-cap' => ['school', 'university', 'learn', 'study', 'mortarboard', 'education', 'ceremony', 'academic', 'hat', 'diploma', 'bachlor\'s', 'master\'s', 'doctorate'],
    'library' => ['books', 'reading', 'written', 'authors', 'stories', 'fiction', 'novels', 'information', 'knowledge', 'education', 'high school', 'university', 'college', 'academy', 'learning', 'study', 'research', 'collection', 'vinyl', 'records', 'albums', 'music', 'package'],
    'church' => ['temple', 'building'],
    'siren' => ['police', 'ambulance', 'emergency', 'security', 'alert', 'alarm', 'light'],
    'shield' => ['cybersecurity', 'secure', 'safety', 'protection', 'guardian', 'armored', 'armoured', 'defense', 'defence', 'defender', 'block', 'threat', 'prevention', 'antivirus', 'vigilance', 'vigilant', 'detection', 'scan', 'find', 'strength', 'strong', 'tough', 'invincible', 'invincibility', 'invulnerable', 'undamaged', 'audit', 'admin', 'verification', 'crest', 'bravery', 'knight', 'foot soldier', 'infantry', 'trooper', 'pawn', 'battle', 'war', 'military', 'army', 'cadet', 'scout'],
    'flame' => ['heat', 'burn', 'light', 'glow', 'ignite', 'passion', 'ember', 'fire', 'lit', 'burning', 'spark', 'embers', 'smoke', 'firefighter', 'fireman', 'department', 'brigade', 'station', 'emergency'],
    'recycle' => ['sustainability', 'salvage', 'arrows'],
    'trash-2' => ['garbage', 'delete', 'remove', 'bin'],
    'vote' => ['vote', 'poll', 'ballot', 'political', 'social', 'check', 'tick'],
    'newspaper' => ['news', 'feed', 'home', 'magazine', 'article', 'headline'],
    'accessibility' => ['disability', 'disabled', 'dda', 'wheelchair'],
    'toilet' => ['toilet', 'potty', 'bathroom', 'washroom'],
    'wifi' => ['connection', 'signal', 'wireless'],
    'fire-extinguisher' => ['flames', 'smoke', 'foam', 'water', 'spray', 'hose', 'firefighter', 'fireman', 'department', 'brigade', 'station', 'emergency', 'suppress', 'compressed', 'tank', 'cylinder', 'safety', 'equipment', 'amenities'],
    'hand' => ['wave', 'move', 'mouse', 'grab'],
    'hand-helping' => ['agreement', 'help', 'proposal', 'charity', 'begging', 'terms'],
    'users' => ['group', 'people'],
    'user' => ['person', 'account', 'contact'],
    'user-round' => ['person', 'account', 'contact'],
    'person-standing' => ['people', 'human', 'accessibility', 'stick figure'],
    'heart-handshake' => ['agreement', 'charity', 'help', 'deal', 'terms', 'emotion', 'together', 'handshake'],
    'captions' => ['closed captions', 'subtitles', 'subhead', 'transcription', 'transcribe', 'dialogue', 'accessibility'],
    'moon' => ['dark', 'night'],
    'id-card' => ['card', 'badge', 'identity', 'authentication', 'secure'],
    'file-text' => ['data', 'txt', 'pdf', 'document'],
    'presentation' => ['screen', 'whiteboard', 'marker pens', 'markers', 'blackboard', 'chalk', 'easel', 'school', 'learning', 'lesson', 'office', 'meeting', 'project', 'planning'],
    'notebook' => ['notepad', 'notes', 'stationery', 'sketchbook', 'moleskine', 'closure', 'strap', 'band', 'elastic', 'organizer', 'organiser', 'planner', 'diary', 'journal', 'writing', 'written', 'writer', 'reading', 'high school', 'university', 'college', 'academy', 'student', 'study', 'homework', 'research'],
    'pencil' => ['rubber', 'edit', 'create', 'draw', 'sketch', 'draft', 'writer', 'writing', 'stationery', 'artist'],
    'pen' => ['pencil', 'change', 'create', 'draw', 'writer', 'writing', 'biro', 'ink', 'marker', 'felt tip', 'stationery', 'artist'],
    'folder' => ['directory'],
    'archive' => ['index', 'backup', 'box', 'storage', 'records'],
];